language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dbernat/dockerwithreact -f Dockerfile.dev .

script:
  - docker run -e CI=true dbernat/dockerwithreact npm run test